version: '3.9'

services:
  server:
    build: .
    ports:
      - '${EXPOSE}:${PORT}'
    depends_on:
      - db
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_USER: '${PG_USERNAME}'
      POSTGRES_DB: '${DATABASE}'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: