version: '3'

services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'merchants'
  server:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - db
    links:
      - "db"

volumes:
  data:

